name: functown
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pip
    - pip:
        - -r requirements.txt
        - pytest
        - pytest-cov
        - pytest-mock
        - pytest-xdist
