name: functown
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pip
    - pip:
        - -r requirements.txt
        - -r requirements-test.txt
        - -r requirements-insights.txt
        - -r requirements-flatbuffer.txt
        - -r requirements-protobuf.txt
        - -r requirements-jwt.txt
        - -r requirements-pandas.txt
