# automatically generated by the FlatBuffers compiler, do not modify

# namespace: example

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InformationList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InformationList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInformationList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InformationList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InformationList
    def Infos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from functown.example.Information import Information
            obj = Information()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InformationList
    def InfosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InformationList
    def InfosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def InformationListStart(builder): builder.StartObject(1)
def Start(builder):
    return InformationListStart(builder)
def InformationListAddInfos(builder, infos): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(infos), 0)
def AddInfos(builder, infos):
    return InformationListAddInfos(builder, infos)
def InformationListStartInfosVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartInfosVector(builder, numElems):
    return InformationListStartInfosVector(builder, numElems)
def InformationListEnd(builder): return builder.EndObject()
def End(builder):
    return InformationListEnd(builder)