# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x10\x66unctown.example\"\xaa\x02\n\x0bInformation\x12\x10\n\x03msg\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05score\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x33\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32%.functown.example.Information.SubInfo\x1ai\n\x07SubInfo\x12\x10\n\x03msg\x18\x01 \x01(\tH\x00\x88\x01\x01\x12;\n\x04type\x18\x02 \x01(\x0e\x32(.functown.example.Information.ImportanceH\x01\x88\x01\x01\x42\x06\n\x04_msgB\x07\n\x05_type\"+\n\nImportance\x12\x08\n\x04HIGH\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x07\n\x03LOW\x10\x02\x42\x06\n\x04_msgB\x05\n\x03_idB\x08\n\x06_score\"?\n\x0fInformationList\x12,\n\x05infos\x18\x01 \x03(\x0b\x32\x1d.functown.example.Informationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFORMATION._serialized_start=36
  _INFORMATION._serialized_end=334
  _INFORMATION_SUBINFO._serialized_start=159
  _INFORMATION_SUBINFO._serialized_end=264
  _INFORMATION_IMPORTANCE._serialized_start=266
  _INFORMATION_IMPORTANCE._serialized_end=309
  _INFORMATIONLIST._serialized_start=336
  _INFORMATIONLIST._serialized_end=399
# @@protoc_insertion_point(module_scope)
